export const ROUTES = {
    home: "/",
    products: "/products",
    productDetails: "/products/:id",
    categories: "/categories",
    offers: "/offers",
    cart: "/cart",
    wishlist: "/wishlist",
    checkout: "/checkout",
    orders: "/orders",
    orderDetails: "/orders/:id",
    profile: "/profile",
    login: "/login",
    register: "/register",

    admin: "/admin",
    adminProducts: "/admin/products",
    adminCategories: "/admin/categories",
    adminOrders: "/admin/orders",
} as const;
