interface OrderSummaryProps { subtotal: number; tax: number; shipping: number; total: number; totalItems: number; loading?: boolean; }
export const OrderSummary = ({ subtotal, tax, shipping, total, totalItems, loading = false }: OrderSummaryProps) => (
    <aside className="h-fit rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_24px_70px_-38px_rgba(15,23,42,0.4)] lg:sticky lg:top-24" aria-labelledby="checkout-summary-title">
        <div className="flex items-center justify-between"><h2 id="checkout-summary-title" className="text-xl font-black text-slate-950">Resumen del pedido</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{totalItems} {totalItems === 1 ? 'producto' : 'productos'}</span></div>
        <dl className="mt-6 space-y-4 text-sm"><div className="flex justify-between text-slate-600"><dt>Subtotal</dt><dd className="font-bold text-slate-900">${subtotal.toFixed(2)}</dd></div><div className="flex justify-between text-slate-600"><dt>Impuestos</dt><dd className="font-bold text-slate-900">${tax.toFixed(2)}</dd></div><div className="flex justify-between text-slate-600"><dt>Envío</dt><dd className="font-bold text-slate-900">{shipping === 0 ? 'Gratis' : `$${shipping.toFixed(2)}`}</dd></div><div className="flex justify-between border-t border-slate-200 pt-5 text-xl font-black text-slate-950"><dt>Total</dt><dd className="text-blue-600">${total.toFixed(2)}</dd></div></dl>
        <button type="submit" disabled={loading} className="mt-6 min-h-13 w-full rounded-xl bg-blue-600 px-5 py-3 font-bold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-200 disabled:cursor-not-allowed disabled:bg-slate-300">{loading ? 'Creando orden…' : 'Confirmar pedido'}</button>
        <p className="mt-4 text-center text-xs font-medium text-slate-500">Revisa el total antes de confirmar el pedido.</p>
    </aside>
);
